---
AWSTemplateFormatVersion: '2010-09-09'
Description: Template to set up a WordPress site on AWS

Parameters:

  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName  
    Description: Enter the name of your existing key pair

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Select your VPC  

  PublicSubnet:
    Type: AWS::EC2::Subnet::Id
    Description: Select public subnet in your VPC

Resources:

  EC2Instance: 
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyPairName
      ImageId: ami-083654bd07b5da81d # Ubuntu 20.04 LTS
      InstanceType: t2.micro
      SecurityGroups: 
        - !Ref WPSecurityGroup
      UserData: 
        Fn::Base64: 
          !Sub |
            #!/bin/bash
            # Install Nginx, PHP, MySQL
            apt update -y
            apt install nginx mariadb-server php-fpm php-mysql -y
            
            # Configure MySQL
            mysql_secure_installation
            
            # Create DB, User, Set Permissions
            mysql -u root -p
              CREATE DATABASE example_db;
              CREATE USER 'example_user'@'localhost' IDENTIFIED BY 'example_pw'; 
              GRANT ALL PRIVILEGES ON example_db.* TO 'example_user'@'localhost';
              FLUSH PRIVILEGES;
              EXIT
            
            # Download and Extract WordPress
            cd /var/www/
            wget https://wordpress.org/latest.tar.gz
            tar xzvf latest.tar.gz 
            rm latest.tar.gz
            
            # Set Ownership and Permissions 
            chown -R www-data:www-data /var/www/wordpress
            chmod -R 755 /var/www/wordpress
            find /var/www/wordpress -type f -exec chmod 644 {} \;
            
            # Configure Nginx Site
            mv /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup
            vim /etc/nginx/sites-available/wordpress.conf
              # paste config
            
            ln -s /etc/nginx/sites-available/wordpress.conf /etc/nginx/sites-enabled
            
            # Restart Services
            systemctl restart nginx
            systemctl restart php7.4-fpm

  WPSecurityGroup:
    Type: AWS::EC2::SecurityGroup  
    Properties:    
      GroupDescription: Enable HTTP and SSH access
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 80
          IpProtocol: tcp  
          ToPort: 80
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
      VpcId: !Ref VpcId

  EIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref EC2Instance

Outputs:
  
  WebsiteURL:
    Value: !Sub 
      - http://${EIP}
      - EIP: !GetAtt EIP.PublicIp